import pandas as pd
import numpy as np
import pandas_ta_classic as ta

def compute_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes technical indicators from a DataFrame of price candles using pandas-ta.
    df must contain: 'open', 'high', 'low', 'close', 'volume'
    Returns a new DataFrame with feature columns added.
    """
    df = df.copy()
    
    if 'time' in df.columns:
        df['time'] = pd.to_datetime(df['time'])
        df = df.sort_values('time').reset_index(drop=True)
        
    for col in ['open', 'high', 'low', 'close', 'volume']:
        df[col] = pd.to_numeric(df[col])
        
    # --- 1. Moving Averages & Trend ---
    df.ta.sma(length=9, append=True)
    df.ta.sma(length=21, append=True)
    df.ta.ema(length=12, append=True)
    df.ta.ema(length=26, append=True)
    
    # Rename for consistency with existing model
    df.rename(columns={'SMA_9': 'sma_9', 'SMA_21': 'sma_21', 'EMA_12': 'ema_12', 'EMA_26': 'ema_26'}, inplace=True)

    # --- 2. MACD ---
    df.ta.macd(fast=12, slow=26, signal=9, append=True)
    df.rename(columns={'MACD_12_26_9': 'macd', 'MACDh_12_26_9': 'macd_hist', 'MACDs_12_26_9': 'macd_signal'}, inplace=True)
    
    # --- 3. RSI ---
    df.ta.rsi(length=14, append=True)
    df.rename(columns={'RSI_14': 'rsi_14'}, inplace=True)
    
    # --- 4. Bollinger Bands ---
    df.ta.bbands(length=20, std=2, append=True)
    df.rename(columns={
        'BBL_20_2.0': 'bb_lower', 
        'BBM_20_2.0': 'bb_middle', 
        'BBU_20_2.0': 'bb_upper',
        'BBB_20_2.0': 'bb_width'
    }, inplace=True)
    
    # --- 5. ATR (Average True Range) ---
    df.ta.atr(length=14, append=True)
    df.rename(columns={'ATRr_14': 'atr_14'}, inplace=True)
    
    # --- 6. Momentum / Rate of Change ---
    df.ta.roc(length=10, append=True)
    df.rename(columns={'ROC_10': 'roc_10'}, inplace=True)
    
    # --- 7. Additional Advanced ML Features ---
    df.ta.stoch(append=True) # Stochastic Oscillator
    df.ta.adx(append=True)   # ADX (Trend Strength)
    df.ta.obv(append=True)   # On-Balance Volume
    
    # Fill NaN values generated by ta indicators
    df.bfill(inplace=True)
    df.ffill(inplace=True)

    # --- 8. Strategy Indicator Encodings & Time Features ---
    close_vals = np.asarray(df['close']).squeeze()
    sma9_vals = np.asarray(df['sma_9']).squeeze()
    sma21_vals = np.asarray(df['sma_21']).squeeze()
    rsi14_vals = np.asarray(df['rsi_14']).squeeze()
    bb_lower_vals = np.asarray(df['bb_lower']).squeeze()
    bb_upper_vals = np.asarray(df['bb_upper']).squeeze()

    if bb_lower_vals.ndim > 1: bb_lower_vals = bb_lower_vals[:, 0]
    if bb_upper_vals.ndim > 1: bb_upper_vals = bb_upper_vals[:, 0]
    if sma9_vals.ndim > 1: sma9_vals = sma9_vals[:, 0]
    if sma21_vals.ndim > 1: sma21_vals = sma21_vals[:, 0]
    if rsi14_vals.ndim > 1: rsi14_vals = rsi14_vals[:, 0]
    if close_vals.ndim > 1: close_vals = close_vals[:, 0]

    df['feat_ma_crossover'] = np.where(sma9_vals > sma21_vals, 1.0, -1.0)
    df['feat_rsi_reversion'] = np.where(rsi14_vals < 30, 1.0, np.where(rsi14_vals > 70, -1.0, 0.0))
    df['feat_bollinger_reversion'] = np.where(close_vals < bb_lower_vals, 1.0, np.where(close_vals > bb_upper_vals, -1.0, 0.0))
    
    # Time & Session Features
    if 'time' in df.columns:
        hours = df['time'].dt.hour
        df['hour_of_day'] = hours
        df['day_of_week'] = df['time'].dt.dayofweek
        df['is_london'] = ((hours >= 7) & (hours < 16)).astype(float)
        df['is_ny'] = ((hours >= 13) & (hours < 21)).astype(float)
        df['is_asian'] = ((hours >= 0) & (hours < 9)).astype(float)

    # Drop duplicate columns to prevent DataFrame indexing issues in XGBoost
    df = df.loc[:, ~df.columns.duplicated()]

    return df

def compute_triple_barrier_labels(df: pd.DataFrame, sl_mult: float = 1.5, tp_mult: float = 3.0, holding_period: int = 20) -> pd.Series:
    """
    Computes Triple-Barrier Method labels matching actual engine SL/TP multipliers:
      - 1: TP barrier hit first (BUY win)
      - 0: SL barrier hit first or time expiry loss
    """
    labels = np.zeros(len(df), dtype=int)
    closes = df['close'].values
    highs = df['high'].values
    lows = df['low'].values
    atrs = df['atr_14'].values if 'atr_14' in df.columns else (highs - lows)

    n = len(df)
    for i in range(n - 1):
        entry_price = closes[i]
        atr = atrs[i] if atrs[i] > 0 else (entry_price * 0.001)
        tp_barrier = entry_price + atr * tp_mult
        sl_barrier = entry_price - atr * sl_mult

        max_look = min(i + 1 + holding_period, n)
        label = 0
        for j in range(i + 1, max_look):
            # Check TP hit
            if highs[j] >= tp_barrier:
                label = 1
                break
            # Check SL hit
            if lows[j] <= sl_barrier:
                label = 0
                break
        labels[i] = label

    return pd.Series(labels, index=df.index, name='target')

