import pandas as pd
import numpy as np
import pandas_ta_classic as ta

def compute_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes technical indicators from a DataFrame of price candles using pandas-ta.
    df must contain: 'open', 'high', 'low', 'close', 'volume'
    Returns a new DataFrame with feature columns added.
    """
    df = df.copy()
    
    if 'time' in df.columns:
        df['time'] = pd.to_datetime(df['time'])
        df = df.sort_values('time').reset_index(drop=True)
        
    for col in ['open', 'high', 'low', 'close', 'volume']:
        df[col] = pd.to_numeric(df[col])
        
    # --- 1. Moving Averages & Trend ---
    df.ta.sma(length=9, append=True)
    df.ta.sma(length=21, append=True)
    df.ta.ema(length=12, append=True)
    df.ta.ema(length=26, append=True)
    
    # Rename for consistency with existing model
    df.rename(columns={'SMA_9': 'sma_9', 'SMA_21': 'sma_21', 'EMA_12': 'ema_12', 'EMA_26': 'ema_26'}, inplace=True)

    # --- 2. MACD ---
    df.ta.macd(fast=12, slow=26, signal=9, append=True)
    df.rename(columns={'MACD_12_26_9': 'macd', 'MACDh_12_26_9': 'macd_hist', 'MACDs_12_26_9': 'macd_signal'}, inplace=True)
    
    # --- 3. RSI ---
    df.ta.rsi(length=14, append=True)
    df.rename(columns={'RSI_14': 'rsi_14'}, inplace=True)
    
    # --- 4. Bollinger Bands ---
    df.ta.bbands(length=20, std=2, append=True)
    df.rename(columns={
        'BBL_20_2.0': 'bb_lower', 
        'BBM_20_2.0': 'bb_middle', 
        'BBU_20_2.0': 'bb_upper',
        'BBB_20_2.0': 'bb_width'
    }, inplace=True)
    
    # --- 5. ATR (Average True Range) ---
    df.ta.atr(length=14, append=True)
    df.rename(columns={'ATRr_14': 'atr_14'}, inplace=True)
    
    # --- 6. Momentum / Rate of Change ---
    df.ta.roc(length=10, append=True)
    df.rename(columns={'ROC_10': 'roc_10'}, inplace=True)
    
    # --- 7. Additional Advanced ML Features ---
    df.ta.stoch(append=True) # Stochastic Oscillator
    df.ta.adx(append=True)   # ADX (Trend Strength)
    df.ta.obv(append=True)   # On-Balance Volume
    
    # Fill NaN values generated by ta indicators
    df.bfill(inplace=True)
    df.ffill(inplace=True)

    # --- 8. Strategy Indicator Encodings ---
    close = df['close']
    df['feat_ma_crossover'] = np.where(df['sma_9'] > df['sma_21'], 1.0, -1.0)
    df['feat_rsi_reversion'] = np.where(df['rsi_14'] < 30, 1.0, np.where(df['rsi_14'] > 70, -1.0, 0.0))
    df['feat_bollinger_reversion'] = np.where(close < df['bb_lower'], 1.0, np.where(close > df['bb_upper'], -1.0, 0.0))
    
    return df
